site_name: ""
site_dir: public

plugins:
  - search:
      lang: ['de', 'en']
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
      minify_js: true
      minify_css: true
      js_files:
          - js/material.js
      css_files:
          - css/material.css
  - i18n:
      default_language: de
      languages:
        de: Deutsch
        en: English

theme:
  name: material
  font: false
  language: de

extra_css:
  - css/material.css
extra_javascript:
  - js/material.js


